---
title: Even greater things
categories: "Engelske sanger"
youtube: op-51tWNYI0
---

Take what I`ve been given  
Make it multiply  
Take the life I`m living  
Make it touch the sky  
You can take us higher  
Than we`ve ever been  
Lord You will inspire  
Lord You always win

Even greater things  
Than have been done before  
Take what we have done  
And make it more  
Even greater things  
Than have been done before  
Even greater things  
Through Christ the Lord

Giant was so mighty  
Over nine feet tall  
David looked so tiny  
Seemed so very small  
But Your hand was with him  
And the stone he slung  
You gave him the vision  
And through You he won

Even greater things  
Than have been done before  
Take what we have done  
And make it more  
Even greater things  
Than have been done before  
Even greater things  
Through Christ the Lord

He was just a pebble  
Made Goliath fall  
I must be more faithful  
I must give my all  
I`ve seen what You can do  
With a stone and sling  
Take this life I give You  
Take my ev`rything

Even greater things  
Than have been done before  
Take what we have done  
And make it more  
Even greater things  
Than have been done before  
Even greater things  
Through Christ the Lord  
(X2)

Even greater things  
Than have been done before  
Take what we have done  
And make it more  
Even greater things  
Than have been done before  
Even greater things  
Through Christ the Lord